###
GET http://localhost:3001

###

GET http://localhost:3001/load

### 
PUT http://localhost:3001/users
Content-Type: application/json

{
  "id": 1002,
  "name": "Jane Doe",
  "username": "janedoe",
  "email": "jane@example.com",
  "address": {
    "street": "Main Ave",
    "suite": "Suite 200",
    "city": "Sampletown",
    "zipcode": "54321",
    "geo": {
      "lat": "12.3456",
      "lng": "78.9012"
    }
  },
  "phone": "987-654-3210",
  "website": "janesite.com",
  "company": {
    "name": "Jane Enterprises",
    "catchPhrase": "Simplifying solutions",
    "bs": "optimize scalable platforms"
  },
  "posts": [
    {
      "id": 9010,
      "userId": 1002,
      "title": "Welcome to My Blog",
      "body": "This is my first blog post. Excited to start this journey!",
      "comments": [
        {
          "id": 8010,
          "postId": 9010,
          "name": "First Fan",
          "email": "fan1@example.com",
          "body": "So happy you're blogging!"
        },
        {
          "id": 8011,
          "postId": 9010,
          "name": "Supporter",
          "email": "support@example.com",
          "body": "Keep writing!"
        }
      ]
    },
    {
      "id": 9011,
      "userId": 1002,
      "title": "Tips for Remote Work",
      "body": "Working remotely has changed how we work. Here are some tips.",
      "comments": [
        {
          "id": 8012,
          "postId": 9011,
          "name": "Remote Pro",
          "email": "remotepro@example.com",
          "body": "Great tips! Totally agree."
        }
      ]
    }
  ]
}

### 
GET http://localhost:3001/users/1001



### 
DELETE http://localhost:3001/users/1001

### 
DELETE http://localhost:3001/users


###
GET http://localhost:3001/all-users

###
GET http://localhost:3001/posts

###
GET http://localhost:3001/comments